version: 0.2

env:
  variables:
    PACKER_VERSION: 1.2.2

phases:
  install:
    commands:
      - ./pack.sh
  pre_build:
    commands: []
  build:
    commands:
      - command
      - command
  post_build:
    commands: []
